name: MSBuild

on:
  push:
    branches: "release"


env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release
  PUBLISH_MANIFEST_FILENAME: publishManifest.json
  VS2019_PROJECT: VisualStudioDiscordRPC.Dev16
  VS2022_PROJECT: VisualStudioDiscordRPC.Dev17
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

  publish:
    needs: build
    steps:
      - name: Publish extension for Visual Studio 2019 to Marketplace
        uses: cezarypiatek/VsixPublisherAction@0.2
        with:
            extension-file: ${{SOLUTION_FILE_PATH}}\bin\Release\{{VS2019_PROJECT}}.vsix
            publish-manifest-file: ${{SOLUTION_FILE_PATH}}\{{VS2019_PROJECT}}\{{PUBLISH_MANIFEST_FILENAME}}
            personal-access-code: ${{ secrets.MARKETPLACE_TOKEN }}

      - name: Publish extension for Visual Studio 2022 to Marketplace
        uses: cezarypiatek/VsixPublisherAction@0.2
        with:
            extension-file: ${{SOLUTION_FILE_PATH}}\bin\Release\{{VS2022_PROJECT}}.vsix
            publish-manifest-file: ${{SOLUTION_FILE_PATH}}\{{VS2022_PROJECT}}\{{PUBLISH_MANIFEST_FILENAME}}
            personal-access-code: ${{ secrets.MARKETPLACE_TOKEN }}
